@asp_website.Server_HostAddress = http://localhost:5129

# For testing only

GET {{asp_website.Server_HostAddress}}/tetrishighscores/
Accept: application/json

###

GET {{asp_website.Server_HostAddress}}/arkanoidhighscores/
Accept: application/json

###

GET {{asp_website.Server_HostAddress}}/dayssinceevents/
Accept: application/json

###

GET {{asp_website.Server_HostAddress}}/testdata/
Accept: application/json

###

GET {{asp_website.Server_HostAddress}}/logoninfo/
Accept: application/json
###
